version: 2
jobs:
  test:
    working_directory: /go/src/github.com/uw-labs/substrate
    docker:
    - image: circleci/golang:1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go get -v -t ./...
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - setup_remote_docker:
          version: 17.06.0-ce
      - run: go test -v ./...
workflows:
  version: 2
  development:
    jobs:
      - test
